version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2024"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  colour-api:
    build: .
    environment:
      DbServer: "ms-sql-server"
      DbPort: "1433"
      DbUser: "SA"
      DbPassword: "Pa55w0rd2024"
      Database: "Colours"
    ports:
      - "7261:8080"